-- Intentionally left without application schema objects.
-- Docker provisions only the PostgreSQL instance for local development.
-- Flyway in the Spring Boot backend is the single source of truth for schema changes.
