spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=myappuser
spring.datasource.password=myapppassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=false
spring.flyway.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://webdevisfun-dev.us.auth0.com/}
app.security.auth0.audience=${AUTH0_AUDIENCE:urn:webdevisfun:api}

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
